import 'es6-promise';
import 'jquery';
import 'angular';
import 'angular-messages';
import 'angular-animate';
import 'angular-aria';
import 'angular-material';
import 'angular-ui-router';
import 'ng-file-upload';